name: unity-catalog
organization: okube
description: Lakehouse - Unity Catalog Configuration
backend: pulumi

pulumi:
  config:

    # Account Provider
    databricks:host: https://accounts.azuredatabricks.net
    databricks:account_id: ${vars.DATABRICKS_ACCOUNT_ID}
    databricks:azure_tenant_id: ${vars.AZURE_TENANT_ID}
    databricks:azure_client_id: ${vars.AZURE_CLIENT_ID}
    databricks:azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
    databricks:auth_type: azure-client-secret

# List of Resources to deploy
resources:

  providers:

    # Dev Workspace Provider
    provider-databricks-dev:
      host: ${vars.DATABRICKS_HOST_DEV}
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
      auth_type: azure-client-secret

    # Prod Workspace Provider
    provider-databricks-prd:
      host: ${vars.DATABRICKS_HOST_PRD}
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
      auth_type: azure-client-secret

  # Account Groups
  databricks_groups: !use resources/groups.yaml

  # Account Users
  databricks_users: !use resources/users.yaml
  databricks_serviceprincipals: !use resources/serviceprincipals.yaml

  # Metastore
  databricks_metastores:
    metastore-lakehouse: !use resources/metastore.yaml

  # External Locations
  databricks_externallocations: !use resources/externallocations.yaml

  # Catalogs
  databricks_catalogs: !use resources/catalogs.yaml

variables:
  databricks_host: https://accounts.azuredatabricks.net
  neptune_dev_client_id: 1f8005d3-5efa-476b-9eb5-11755fea1128
  neptune_prd_client_id: 78f6cf4f-0c24-4977-92fc-562a60358466
  workspace_id_dev: 4623853922539974
  workspace_id_prd: 1985337240298151
  metastore_storage_location: abfss://metastore@o3stglakehousedev.dfs.core.windows.net/
  metastore_prd_storage_location: abfss://metastore@o3stglakehouseprd.dfs.core.windows.net/
  tables_storage_location_dev: abfss://tables@o3stglakehousedev.dfs.core.windows.net/
  tables_storage_location_prd: abfss://tables@o3stglakehouseprd.dfs.core.windows.net/
  landing_storage_location_dev: abfss://landing@o3stglakehousedev.dfs.core.windows.net/
  landing_storage_location_prd: abfss://landing@o3stglakehouseprd.dfs.core.windows.net/


environments:
  global: {}
