name: unity-catalog
organization: Okube
description: Lakehouse - Unity Catalog Configuration
backend: terraform
terraform:
  backend: !use terraform-config/backend.yaml

# List of Resources to deploy
resources:
  providers:
    databricks:
      host: ${vars.DATABRICKS_HOST}
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
      auth_type: azure-client-secret

  # Storage Credentials
  databricks_storagecredentials: !use resources/storagecredentials.yaml

  # External Locations
  databricks_externallocations: !use resources/externallocations.yaml

  # Catalogs
  databricks_catalogs: !use resources/catalogs.yaml


environments:
  dev:
    variables:
      env: dev
  prd:
    variables:
      env: prd
