name: unity-catalog
organization: okube
description: Lakehouse - Unity Catalog
backend: pulumi

pulumi:
  config:
    databricks:account_id: ${vars.DATABRICKS_ACCOUNT_ID}
    databricks:auth_type: azure-cli
    databricks:host: https://accounts.azuredatabricks.net

resources:
  providers:
    provider-workspace-neptune:
      host: ${vars.DATABRICKS_HOST}  # this is the account URL
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
  databricks_groups: ${include.resources/groups.yaml}
  databricks_users: ${include.resources/users.yaml}
  databricks_serviceprincipals: ${include.resources/serviceprincipals.yaml}
  databricks_metastores:
    metastore-lakehouse: ${include.resources/metastore.yaml}
  databricks_externallocations: ${include.resources/externallocations.yaml}
  databricks_catalogs: ${include.resources/catalogs.yaml}
  # TODO: init scripts is challenging because terraform and pulumi do not share the same properties.

variables:
  databricks_host: https://accounts.azuredatabricks.net
  neptune_dev_client_id: 1f8005d3-5efa-476b-9eb5-11755fea1128
  neptune_prd_client_id: 78f6cf4f-0c24-4977-92fc-562a60358466
  intelli5_dev_client_id: 861e3a1c-5245-4065-80a3-71373f401147
  intelli5_prd_client_id: 2f9f1626-dc78-4cd3-8fc0-3c1d03cffa6d
  workspace_id_dev: 4623853922539974
  workspace_id_prd: 1985337240298151
  metastore_storage_location: abfss://metastore@o3stglakehousedev.dfs.core.windows.net/
  metastore_prd_storage_location: abfss://metastore@o3stglakehouseprd.dfs.core.windows.net/
  landing_storage_location_dev: abfss://landing@o3stglakehousedev.dfs.core.windows.net/
  landing_storage_location_prd: abfss://landing@o3stglakehouseprd.dfs.core.windows.net/
