name: workflows
organization: okube
description: Lakehouse - Workflows
backend: pulumi
pulumi:
  config:
    databricks:host: ${vars.DATABRICKS_HOST}
    databricks:azure_client_id: ${vars.AZURE_CLIENT_ID}
    databricks:azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
    databricks:azure_tenant_id: ${vars.AZURE_TENANT_ID}
    databricks:auth_type: azure-client-secret
resources:
  databricks_workspacetrees: !use resources/workspacetrees.yaml
  databricks_queries: !use resources/queries.yaml
  databricks_pythonpackages: !use resources/pythonpackages.yaml
  pipelines:
    pl-stock-prices: !use resources/pl-stock-prices.yaml
    dlt-stock-prices: !use resources/dlt-stock-prices.yaml
  databricks_jobs:
    job-dlt-stock-prices: !use resources/job-dlt-stock-prices.yaml
variables:
  laktory_package: laktory==0.8.10
#  laktory_package: git+https://github.com/okube-ai/laktory.git@fix/qualitymonitor
  wheel_filepath: /Workspace${vars.workspace_laktory_root}wheels/lake-0.0.1-py3-none-any.whl

environments:
  debug:
    variables:
      env: dev

  dev:
    variables:
      env: dev
      is_dev: true
      sql_tasks_warehouse_id: 4d0b09d503ba808f
  prd:
    variables:
      env: prd
      is_dev: false
      sql_tasks_warehouse_id: 5beb0035099473f4
