name: workflows
organization: okube
description: Lakehouse - Workflows
backend: pulumi
pulumi:
  config:
    databricks:host: ${vars.DATABRICKS_HOST}
    databricks:azure_client_id: ${vars.AZURE_CLIENT_ID}
    databricks:azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
    databricks:azure_tenant_id: ${vars.AZURE_TENANT_ID}
resources:
  databricks_notebooks: !use resources/notebooks.yaml
  databricks_workspacefiles: !use resources/workspacefiles.yaml
  databricks_queries: !use resources/queries.yaml
  pipelines:
    pl-stock-prices: !use resources/pl-stock-prices.yaml
    dlt-stock-prices: !use resources/dlt-stock-prices.yaml
  databricks_jobs:
    job-dlt-stock-prices: !use resources/job-dlt-stock-prices.yaml
variables:
#  laktory_package: laktory==0.7.2
    laktory_package: "git+https://github.com/okube-ai/laktory.git@feat/lac-working"

environments:
  debug:
    variables:
      env: dev
#    resources:
#      pipelines:
#        dlt-stock-prices:
#          nodes:
#            0:
#              source:
#                limit: 100
  dev:
    variables:
      env: dev
      is_dev: true
      sql_tasks_warehouse_id: a6bc05a0fc5e55ae
  prd:
    variables:
      env: prd
      is_dev: false
      sql_tasks_warehouse_id: 5beb0035099473f4
