name: laktory run job

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: ./workspace
      databricks_host:
        type: string
        required: true
      job_name:
        type: string
        required: true
    secrets:
      azure_client_id:
        description: d
      azure_client_secret:
        description: d
      azure_tenant_id:
        description: d

env:
  AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
  AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
  AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}
  DATABRICKS_HOST: ${{ inputs.databricks_host }}

jobs:
  laktory-run-job:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: env vars
        run: |
          import os
          for k, v in os.environ.items():
            print(k, "|", v)
        shell: python

      - name: Setup python environment
        run: |
          pip install -r requirements.txt
          pip install -U git+https://github.com/okube-ai/laktory.git@cli_run
        working-directory: ${{ inputs.working-directory }}

      - name: laktory run
        run: |
          laktory run -e ${{ inputs.env }} -j ${{ inputs.job_name }} -a WAIT
        working-directory: ${{ inputs.working-directory }}
