name: laktory deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: ./workspace
      databricks_host:
        type: string
        required: true
    secrets:
      azure_client_id:
        required: False
      azure_client_secret:
        required: False
      azure_tenant_id:
        required: False
      databricks_account_id:
        required: False
      databricks_host:
        required: False
      databricks_token:
        required: False
      pulumi_access_token:
        required: False


# TODO: Figure out a way not to have to explicitly define each possible
# environment variable
env:
  AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
  AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
  AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}
  DATABRICKS_ACCOUNT_ID: ${{ secrets.databricks_account_id }}
  DATABRICKS_HOST: ${{ inputs.databricks_host }}
  DATABRICKS_TOKEN: ${{ secrets.databricks_token }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}

jobs:
  laktory-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: env vars
        run: |
          import os
          for k, v in os.environ.items():
            print(k, "|", v)
        shell: python

      - name: Setup python environment
        run: |
          pip install -r requirements.txt
        working-directory: ${{ inputs.working-directory }}

      - name: laktory deploy
        run: |
          laktory deploy -e ${{ inputs.env }} --yes
        working-directory: ${{ inputs.working-directory }}
