name: laktory preview

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: ./workspace

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


jobs:
  laktory-preview:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          python-version: 3.12

      - name: env vars
        run: |
          import os
          for k, v in os.environ.items():
            print(k, "|", v)
        shell: python

      - name: Setup python environment
        run: |
          pip install -r requirements.txt
        working-directory: ${{ inputs.working-directory }}

      - name: laktory preview
        run: |
          laktory preview -e ${{ inputs.env }}
        working-directory: ${{ inputs.working-directory }}
