name: laktory deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: false
        default: ''
      working-directory:
        type: string
        required: false
        default: ./workspace
    secrets:
      azure_client_id:
        required: False
      azure_client_secret:
        required: False
      azure_tenant_id:
        required: False
      databricks_account_id:
        required: False


# TODO: Figure out a way not to have to explicitly define each possible
# environment variable
env:
  AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
  AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
  AZURE_TENANT_ID: ${{ secrets.azure_tenant_id }}
  DATABRICKS_ACCOUNT_ID: ${{ secrets.databricks_account_id }}
  DATABRICKS_TOKEN_OSOUCY: token_osoucy  # required to test deployment of databricks secret in workspace stack
  LAKTORY_CLI_RAISE_EXTERNAL_EXCEPTIONS: true

jobs:
  laktory-deploy:
#    runs-on: ubuntu-latest
    runs-on: ubuntu-22.04  # ubuntu-latest does not seem to have terraform available anymore
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          python-version: 3.12

      - name: env vars
        run: |
          import os
          for k, v in os.environ.items():
            print(k, "|", v)
        shell: python

      - name: Setup python environment
        run: |
          uv pip install -r requirements.txt
        working-directory: ${{ inputs.working-directory }}

      - name: laktory deploy
        run: |
          ENV_FLAG=""
          if [[ -n "${{ inputs.env }}" ]]; then ENV_FLAG="-e ${{ inputs.env }}"; fi
          laktory init $ENV_FLAG --options -reconfigure
          laktory deploy $ENV_FLAG --yes
        working-directory: ${{ inputs.working-directory }}
