name: laktory preview

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: ./workspace

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


jobs:
  laktory-preview:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup python environment
        run: |
          pip install -r requirements.txt
          pip install -U git+https://github.com/okube-ai/laktory.git@cli_run
        working-directory: $${{ inputs.working-directory }}

      - name: laktory preview
        run: |
          laktory preview -e dev
        working-directory: $${{ inputs.working-directory }}
