name: dab deploy

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: ./workflows-dab
      laktory_branch:
        type: string
        required: false
        default: ''
    secrets:
      azure_client_id:
        required: false
      azure_client_secret:
        required: false
      azure_tenant_id:
        required: false

env:
  ARM_CLIENT_ID: ${{ secrets.azure_client_id }}
  ARM_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
  ARM_TENANT_ID: ${{ secrets.azure_tenant_id }}
#  DATABRICKS_TOKEN: ${{ secrets.databricks_token }}
  DATABRICKS_AUTH_TYPE: azure-client-secret

jobs:
  dab-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          python-version: "3.12"

      - name: Set up venv
        run: uv sync --dev
        working-directory: ${{ inputs.working-directory }}

      - name: Override laktory version
        if: ${{ inputs.laktory_branch != '' }}
        run: |
          VIRTUAL_ENV=$(pwd)/.venv uv pip install "git+https://github.com/okube-ai/laktory.git@${{ inputs.laktory_branch }}"
        working-directory: ${{ inputs.working-directory }}

      - name: Update laktory
        run: |
          uv run laktory version
        working-directory: ${{ inputs.working-directory }}

      - name: Bundle deploy
        run: |
          BUNDLE_VARS=""
          if [[ -n "${{ inputs.laktory_branch }}" ]]; then
            BUNDLE_VARS="--var laktory_package=git+https://github.com/okube-ai/laktory.git@${{ inputs.laktory_branch }}"
          fi
          databricks bundle deploy --target ${{ inputs.target }} $BUNDLE_VARS
        working-directory: ${{ inputs.working-directory }}
