name: deploy workflow

on:
  workflow_call:

jobs:
  release-approval:
    runs-on: ubuntu-latest
    steps:

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: osoucy
          minimum-approvals: 1
