name: dab-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-dev:
    uses: ./.github/workflows/_job_dab_deploy.yml
    with:
      target: dev
    secrets: inherit

  run-job-stock-prices:
    needs: deploy-dev
    uses: ./.github/workflows/_job_dab_run.yml
    with:
      target: dev
      resource: job-stock-prices
    secrets: inherit

  run-pl-tpch:
    needs: deploy-dev
    uses: ./.github/workflows/_job_dab_run.yml
    with:
      target: dev
      resource: pl-tpch
    secrets: inherit

  run-pl-taxi-trips:
    needs: deploy-dev
    uses: ./.github/workflows/_job_dab_run.yml
    with:
      target: dev
      resource: pl-taxi-trips
    secrets: inherit

  prd-approval:
    needs: [run-job-stock-prices, run-pl-tpch, run-pl-taxi-trips]
    uses: ./.github/workflows/_job_release_approval.yml
    secrets: inherit

  deploy-prd:
    needs: prd-approval
    uses: ./.github/workflows/_job_dab_deploy.yml
    with:
      target: prd
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID_PRD }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET_PRD }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
