name: deploy-run-dev

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      laktory_branch:
        description: 'Laktory git branch to test (leave empty to use pinned version)'
        required: false
        default: ''

jobs:

  deploy-account:
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      working-directory: ./account
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID_PRD }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET_PRD }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      databricks_account_id: ${{ secrets.DATABRICKS_ACCOUNT_ID }}

  deploy-unity-catalog:
    needs: deploy-account
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      env: dev
      working-directory: ./unity-catalog
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit

  deploy-workspace:
    needs: deploy-unity-catalog
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      env: dev
      working-directory: ./workspace
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit

  deploy-workflows:
    needs: deploy-workspace
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      env: dev
      working-directory: ./workflows
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit

  deploy-dab:
    needs: deploy-workspace
    uses: ./.github/workflows/_job_dab_deploy.yml
    with:
      target: dev
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit

  run-job-stock-prices:
    needs: [deploy-workflows]
    uses: ./.github/workflows/_job_laktory_run_job.yml
    with:
      env: dev
      working-directory: ./workflows
      job_name: job-stock-prices
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit

  run-pl-taxi-trips:
    needs: [deploy-workflows]
    uses: ./.github/workflows/_job_laktory_run_job.yml
    with:
      env: dev
      working-directory: ./workflows
      job_name: pl-taxi-trips
      laktory_branch: ${{ inputs.laktory_branch || '' }}
    secrets: inherit
