name: laktory-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-dev:
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      env: dev
      working-directory: ./workflows
      databricks_host: 'adb-4623853922539974.14.azuredatabricks.net'
    secrets: inherit

  run-job-stock-prices:
    needs: deploy-dev
    uses: ./.github/workflows/_job_laktory_run_job.yml
    with:
      env: dev
      working-directory: ./workflows
      databricks_host: 'adb-4623853922539974.14.azuredatabricks.net'
      job_name: job-stock-prices
    secrets: inherit

  run-pl-taxi-trips:
    needs: deploy-dev
    uses: ./.github/workflows/_job_laktory_run_dlt.yml
    with:
      env: dev
      working-directory: ./workflows
      databricks_host: 'adb-4623853922539974.14.azuredatabricks.net'
      dlt_name: pl-taxi-trips
    secrets: inherit

  prd-approval:
    needs: [run-job-stock-prices, run-pl-taxi-trips]
    uses: ./.github/workflows/_job_release_approval.yml
    secrets: inherit

  deploy-prd:
    needs: prd-approval
    uses: ./.github/workflows/_job_laktory_deploy.yml
    with:
      env: prd
      working-directory: ./workflows
      databricks_host: 'adb-1985337240298151.11.azuredatabricks.net'
    secrets:
      pulumi_access_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID_PRD }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET_PRD }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
