name: laktory-preview

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  laktory-preview-dev:
    uses: ./.github/workflows/_job_laktory_preview.yml
    with:
      env: dev
      working-directory: ./workspace
    secrets: inherit
