name: preview

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup python environment
        run: |
          pip install -r requirements.txt
        working-directory: ./workspace

      - name: laktory preview
        run: |
          set -e
          laktory preview -e dev
        working-directory: ./workspace
        continue-on-error: false
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

#      - name: laktory deploy
#        run: |
#          set -e
#          laktory deploy -e dev --pulumi-options "--yes"
#        working-directory: ./workspace
#        continue-on-error: false
#        env:
#          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
#        env:
#          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
#          DATABRICKS_BUNDLE_ENV: dev

#      - name: Run tests
#        if: ${{ env.run_tests == 'true' && success()}}
#        run: make dev test
#        env:
#          AWS_REGION: ${{ vars.AWS_REGION }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
#          DATABRICKS_WAREHOUSE_ID: ${{ vars.DATABRICKS_WAREHOUSE_ID }}
#          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
#          LAKEHOUSE_SA_CONN_STR: ${{ secrets.LAKEHOUSE_SA_CONN_STR }}
#          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

#      - name: Publish test coverage
#        uses: codecov/codecov-action@v1
