name: workspace
organization: okube
description: Lakehouse - Workspace
backend: pulumi
pulumi:
  config:
    databricks:host: ${vars.DATABRICKS_HOST}
    databricks:azure_client_id: ${vars.AZURE_CLIENT_ID}
    databricks:azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
    databricks:azure_tenant_id: ${vars.AZURE_TENANT_ID}
  outputs:
    directory-laktory-queries: folders/${resources.directory-laktory-queries.objectId}
    warehouse-default-data-source-id: ${resources.warehouse-default.dataSourceId}
    warehouse-default-id: ${resources.warehouse-default.id}
resources:
  databricks_secretscopes: ${include.resources/secretscopes.yaml}
  databricks_directories: ${include.resources/directories.yaml}
  databricks_clusters: ${include.resources/clusters.yaml}
  databricks_warehouses: ${include.resources/warehouses.yaml}
environments:
  dev:
    variables:
      env: dev
  prd:
    variables:
      env: prd