name: workspace
description: Lakehouse - Workspace
engine: pulumi
config:
  databricks:host: ${var.DATABRICKS_HOST}
  databricks:azure_client_id: ${var.AZURE_CLIENT_ID}
  databricks:azure_client_secret: ${var.AZURE_CLIENT_SECRET}
  databricks:azure_tenant_id: ${var.AZURE_TENANT_ID}
resources:
  notebooks: ${include.resources/notebooks.yaml}
  workspacefiles: ${include.resources/workspacefiles.yaml}
  sqlqueries: ${include.resources/sqlqueries.yaml}
  pipelines:
    pl-stock-prices: ${include.resources/pl-stock-prices.yaml}
  jobs:
    job-stock-prices: ${include.resources/job-stock-prices.yaml}

environments:
  dev:
    variables:
      env: dev
      is_dev: true
      sql_tasks_data_source_id: d5e40c23-67bd-4442-a713-676014169664
      directory-laktory-queries-views: folders/376437268450950
      sql_tasks_warehouse_id: 08b717ce051a0261
